spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: campus-repair
  # JWT配置
  security:
    jwt:
      secret: ${JWT_SECRET:your_jwt_secret_key_must_be_very_long_and_secure_at_least_256_bits}
      expiration: 86400000  # 24小时
  # 数据库初始化配置
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# 通用配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zsxyww.backend.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-prefix: ww_

# 文件上传配置
upload:
  path: ${UPLOAD_PATH:./uploads}
  max-size: 10MB
  allowed-types:
    - image/jpeg
    - image/png
    - image/gif
    - image/bmp
    - image/webp
  url-prefix: /uploads/

# springdoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zsxyww.backend.controller
  default-flat-param-object: true
  show-actuator: false

# knife4j配置
knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-document-manage: true
    enable-home-custom: true
    enable-search: true
    enable-footer: false
    enable-footer-custom: false
    enable-host-cache: false
    enable-host: false
    enable-request-cache: true