spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:campus_repair}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:repair_user}
    password: ${MYSQL_PASSWORD:repair_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库初始化配置
    sql:
      init:
        mode: never
    
  # Redis配置
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:your_redis_password}
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    
  # RabbitMQ配置
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:repair_user}
    password: ${RABBITMQ_PASSWORD:your_rabbitmq_password}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
        
# 日志配置
logging:
  level:
    root: INFO
    com.zsxyww.backend: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# 开发环境特定配置
dev:
  # 是否启用Swagger
  swagger-enabled: true
  # 是否打印SQL
  show-sql: true
  # 是否允许跨域
  cors-enabled: true
  # 是否启用Redis缓存
  cache-enabled: true
  # 是否启用RabbitMQ
  mq-enabled: true
  # 是否启用文件上传
  upload-enabled: true
  # 是否启用邮件发送
  mail-enabled: false
  # 是否启用短信发送
  sms-enabled: false
  # 是否启用验证码
  captcha-enabled: false
  # 是否启用WebSocket
  websocket-enabled: false
  # 是否启用定时任务
  scheduler-enabled: false
  # 是否启用异步任务
  async-enabled: true
  # 是否启用事务
  transaction-enabled: true
  # 是否启用AOP
  aop-enabled: true
  # 是否启用监控
  monitor-enabled: false