spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:mysql}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      
  # Redis配置
  redis:
    host: ${SPRING_REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        
  # RabbitMQ配置
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
      
      
# 日志配置
logging:
  level:
    root: WARN
    com.campus.repair: INFO
  file:
    name: /var/log/campus-repair/application.log
    max-size: 100MB
    max-history: 30
    
# 安全配置
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    
# 文件上传配置
upload:
  path: ${UPLOAD_PATH:/data/uploads}
  max-size: 10MB 

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    sql-session-factory:
      mapper-locations: classpath*:mapper/*.xml
  # 分页插件配置
  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql 