spring:
  profiles:
    # active: ${SPRING_PROFILES_ACTIVE:dev}
    active: test
  application:
    name: campus-repair
  # 数据库初始化配置
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8
  docker:
    compose:
      enabled: false

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# 通用配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zsxyww.backend.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 文件上传配置
upload:
  path: ${UPLOAD_PATH:./uploads}
  max-size: 10MB
  allowed-types:
    - image/jpeg
    - image/png
    - image/gif
    - image/bmp
    - image/webp
  url-prefix: /uploads/

# 安全配置
security:
  jwt:
    secret: ${JWT_SECRET:your_jwt_secret_key}
    expiration: 86400000 # 24小时
    token-prefix: "Bearer "
    header: "Authorization"
    parameter-name: "token"
    ignore-urls:
      - /api/auth/login
      - /api/auth/register
      - /api/auth/captcha
      - /api/knowledge/articles/list
      - /api/knowledge/articles/detail/**
      - /api/knowledge/categories/tree
      - /uploads/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html
      - /webjars/**

# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-document-manage: true
    enable-home-custom: true
    enable-search: true
    enable-footer: false
    enable-footer-custom: false
    enable-host-cache: false
    enable-host: false
    enable-request-cache: true